server {
    listen 80;
    listen [::]:80;

    server_name kinesis.com.ar;

    root /var/www/kinesis/backoffice;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
